import { defineField, defineType } from "sanity";
import { usdPriceField } from "./shared";

export const rifle = defineType({
  name: "rifle",
  title: "Rifle Build",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "configurator", title: "Configurator" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      group: "content",
      options: {
        list: [
          { title: "Hunting", value: "hunting" },
          { title: "Long Range", value: "long-range" },
          { title: "Safari / Dangerous Game", value: "safari" },
          { title: "Precision", value: "precision" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "featured",
      title: "Featured on home page",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({
      name: "startingAt",
      title: "Starting price",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      group: "content",
      rows: 5,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroImage",
      title: "Hero image",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", title: "Alt text", type: "string" }),
      ],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      group: "content",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            defineField({ name: "alt", title: "Alt text", type: "string" }),
            defineField({ name: "caption", title: "Caption", type: "string" }),
          ],
        },
      ],
    }),
    defineField({
      name: "specs",
      title: "Specifications",
      type: "object",
      group: "content",
      fields: [
        defineField({ name: "action", title: "Action", type: "string" }),
        defineField({ name: "caliber", title: "Caliber", type: "string" }),
        defineField({ name: "barrel", title: "Barrel", type: "string" }),
        defineField({ name: "barrelLength", title: "Barrel length", type: "string" }),
        defineField({ name: "twistRate", title: "Twist rate", type: "string" }),
        defineField({ name: "stock", title: "Stock / chassis", type: "string" }),
        defineField({ name: "bottomMetal", title: "Bottom metal", type: "string" }),
        defineField({ name: "trigger", title: "Trigger", type: "string" }),
        defineField({ name: "muzzleBrake", title: "Muzzle brake", type: "string" }),
        defineField({ name: "finish", title: "Finish", type: "string" }),
        defineField({ name: "weight", title: "Weight", type: "string" }),
        defineField({ name: "overallLength", title: "Overall length", type: "string" }),
        defineField({ name: "accuracy", title: "Accuracy guarantee", type: "string" }),
        defineField({ name: "magazine", title: "Magazine", type: "string" }),
      ],
    }),
    defineField({
      name: "highlights",
      title: "Build highlights",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "primaryUse",
      title: "Primary use",
      type: "string",
      group: "configurator",
      description: "Shown in the build configurator (e.g. Ultralight Backcountry)",
    }),
    defineField({
      name: "chassis",
      title: "Chassis / platform",
      type: "string",
      group: "configurator",
      description: "Stock or chassis name for configurator specs",
    }),
    defineField({
      name: "actionName",
      title: "Action name",
      type: "string",
      group: "configurator",
      description: "Action label for configurator specs",
    }),
    defineField({
      name: "barrelSummary",
      title: "Barrel summary",
      type: "string",
      group: "configurator",
      description: 'Short barrel line for configurator (e.g. 22" Carbon Wrapped)',
    }),
    usdPriceField("configuratorPrice", "Configurator price", {
      group: "configurator",
      description: "Platform price shown in the build configurator",
    }),
    defineField({
      name: "configuratorPriceCents",
      title: "Configurator price (legacy cents)",
      type: "number",
      group: "configurator",
      hidden: true,
    }),
    defineField({
      name: "showInConfigurator",
      title: "Show in configurator",
      type: "boolean",
      group: "configurator",
      initialValue: true,
    }),
    defineField({
      name: "configuratorImage",
      title: "Configurator card image",
      type: "image",
      group: "configurator",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", title: "Alt text", type: "string" }),
      ],
      description: "Optional override; defaults to hero image",
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "tagline", media: "heroImage" },
  },
});
